Don't print "summarized" arrays into the SLiM script.
With long genomic element intervals arrays, we currently get:

```
stdpopsim.slim_engine.SLiMException: slim exited with code 1.
ERROR (EidosScript::Parse_PrimaryExpr): unexpected token '.'.

Error on script line 35, character 64:

    initializeGenomicElement(0, c(15690025, 15695370, 15695644, ..., 50785172, 50788749, 50788891), c(15690708, 15695484, 15695817, ..., 50785292, 50788797, 50789352));
                                                                ^
```

In addition, we had three different formats for the output arrays,
so this patch makes all printed arrays use a single function.